<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>1.0.0</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Stuff I keep rewriting for lightweight patching.</Description>
    <PackageProjectUrl>https://github.com/craigduggan90/Beans/tree/main/src/Beans.Patchable</PackageProjectUrl>
  </PropertyGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="Beans.Patchable.UnitTests"/>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
